version: '3'

services:
    web1:
        image: php:8.2.28-apache
        container_name: web1
        volumes:
          - ./web1:/var/www/html
        ports:
          - "8080:80"
        working_dir: /var/www/html
        command: ["/bin/sh", "-c", "[ -d /var/www/html/flag ] && cp -r /var/www/html/flag / && rm -rf /var/www/html/flag; apache2-foreground"]
    web3:
        image: php:8.2.28-apache
        container_name: web3
        volumes:
          - ./web3:/var/www/html
        ports:
          - "8082:80"
        working_dir: /var/www/html
